job ( "${YOUR_USER_NAME}BuildCommit" ) {

	description ( 'generated by Job DSL on ' + new Date ( ) )
	logRotator  ( -1, 50, -1, 50 )
	scm {
		git {
			branch ( 'origin/master' )
			remote {
				url         ( "${GIT_REPO_SSH_URL}"  )
				credentials ( "${GIT_CREDENTIAL_ID}" )
			}
		}
	}

	steps {
		shell (
"""
echo
mvn clean install
""")
	}
}
