job ( "${YOUR_USER_NAME}BuildCommit" ) {

	description ( 'generated by Job DSL on ' + new Date ( ) )
	logRotator  ( -1, 50, -1, 50 )
/*
	scm {
		git {
			remote {
				url         ( ${GIT_REPO_SSH_URL} )
				credentials ( 'insert your credentials id here' )
			}
			branch ( 'origin/master' )
		}
	}
*/
}
