job ( "${YOUR_USER_NAME}BuildCommit" ) {

	description ( 'generated by Job DSL on ' + new Date ( ) )
	logRotator  ( -1, 50, -1, 50 )
	scm {
		git {
			branch ( 'origin/master' )
			remote {
				url         ( "${GIT_REPO_SSH_URL}"  )
				credentials ( "${GIT_CREDENTIAL_ID}" )
			}
		}
	}

	steps {
		shell (
"""
echo
mvn clean install
""")
	}

	publishers {
        downstreamParameterized {
            trigger( "${YOUR_USER_NAME}Deploydev") {
                condition('UNSTABLE_OR_BETTER')
                parameters {
                    predefinedProp ( "ARTIFACT_S3_URL", "insert_s3_url" )
                }
            }
        }
    }
}
